### ISSUE TITLE
sdk version in global.json not matching installed sdk version

### ISSUE THREAD

**Issue by ZimmerD** [dotnetlife/FSharpReady#1]
When I set up the project the sdk version referenced in the global.json (3.1.4?) did not match the one installed (in my case 3.1.201). As a result the solution is can not be displayed correctly and will also not build. After setting the version manually everything works as expected.

Proposed solution:

- Infer installed dotnet version

**Comment by HLWeil** [comment]
Fixed in cab43bc5ecff9c1ec7e32f703ba76bcbc27f45be
